server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**

            - id: hotel-service
              uri: lb://hotel-service
              predicates:
                - Path=/hotel/**

            - id: rating-service
              uri: lb://rating-service
              predicates:
                - Path=/rating/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
