spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
